### ISSUE TITLE
Meaningful operationIds in OpenApi spec

### ISSUE THREAD

**Issue by sebplorenz** [FraunhoferISST/DataspaceConnector#423] opened 2021-07-14 08:50 UTC
Hi, the OpenApi spec of the DSC contains auto-generated operation ids like this:

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/5d2425c5d3f6c487a52563f79d974ba3e7abf7c9/openapi.yaml#L694-L699

or this:

https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/5d2425c5d3f6c487a52563f79d974ba3e7abf7c9/openapi.yaml#L804-L809

Since the clients that are generated out of this specification are meant for human use it would be nice if the operationIds would have a meaningful name. For the two examples above this could be getRepresentationRequests and getRepresentationOffers.

**Comment by juliapampus** [comment] 2021-07-14 08:52
Duplicate of International-Data-Spaces-Association/DataspaceConnector#15

**Comment by juliapampus** [comment] 2021-11-02 09:11
Duplicate of International-Data-Spaces-Association/DataspaceConnector#15

**Closed as completed by juliapampus** 2021-11-02 09:11 UTC
Labels: docs, open for contribution
