### ISSUE TITLE
Swagger-Docs: Update local data needs specific content type

### ISSUE THREAD

**Issue by SebastianOpriel** [FraunhoferISST/DataspaceConnector#764] opened 2021-11-26 18:36 UTC
**Describe the bug**
Swagger UI shows an Endpoint "Artifacts" > "PUT /api/artifacts/{id}/data"
Executing it, results in a response HTTP:500 and Error:
```
{"message": "An error occurred. Please try again later."}
```
with exception: 
```
could not resolve parameter [1] in public org.springframework.http.ResponseEntity<java.lang.Void> io.dataspaceconnector.controller.resource.type.ArtifactController.putData(java.util.UUID,byte[]) throws java.io.IOException: Content-Type cannot contain wildcard type '*'
```

After looking into the code, you define the accepted contents as `consumes = "*/*"`, see: 
https://github.com/International-Data-Spaces-Association/DataspaceConnector/blob/a3116a4f6c75ec3a0dfebb1583ad32ed3a20e585/src/main/java/io/dataspaceconnector/controller/resource/type/ArtifactController.java#L247

The problem is, that swagger-ui uses the `"*/*"` as content type:
```
curl -X 'PUT' \
  'https://sovity1.connector.demo.dataspace.sovity.de/api/artifacts/20f8bb1f-f028-4e8c-b41d-77fc65c7f516/data' \
  -H 'accept: */*' \
  -H 'Content-Type: */*' \
  -d 'data'
```

Executing this request e.g. with postman and header field `Content-Type: text/plain` works perfectly.

**Comment by juliapampus** [comment] 2021-12-03 09:47
Duplicate of #595

**Closed as completed** 2021-12-17 07:09 UTC
